project:
  type: website

website:
  title: false
  navbar:
    left:
      - logo: "images/logo.jpg"
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: videos.qmd
        text: Videos
      - href: contact.qmd
        text: Contact Us
    right: 
      - search: true
  favicon: "images/favicon.png"
  page-footer:
    right: "Check out our [YouTube Channel](https://www.youtube.com/@thegreenyardaz)"
  google-analytics: ""
    

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
