project:
  type: website
website:
  title: "The Green Yard"
  navbar:
    logo: "images/logo.jpg"
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: videos.qmd
        text: Videos
      - href: contact.qmd
        text: Contact Us
  format:
  html:
    head:
      extra:
        - "<style>"
        - "  .navbar-logo {"
        - "    max-width: 200px;
        - "    height: auto; /* Maintain aspect ratio */"
        - "  }"
        - "</style>"
    theme: default

  favicon: "images/favicon.png"
  page-footer:
    right: "Check out our [YouTube Channel](https://www.youtube.com/@thegreenyardaz)"
  google-analytics: ""
    

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
