---
layout: default
title: Home
---

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; width: 100%; height: auto;">
  <iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="https://www.youtube.com/embed/_qtJWZNEXuc?autoplay=1&mute=1&loop=1&playlist=_qtJWZNEXuc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>

# Welcome to My GitHub Pages Site

Here is some content for your homepage.



# Welcome to The Green Yard!

Hello and welcome to The Green Yard! My name is Schuyler, and I'm excited to share my journey with you. My wife and I just moved into a new house in the heart of Phoenix, and we're on a mission to transform our brown, slightly landscaped, and mostly unusable yard into a beautiful, green, profitable, and livable landscape.

## About Me

I'm passionate about sustainability, gardening, and creating beautiful outdoor spaces. Join me as I document the process of turning our yard into a thriving oasis. From planning and planting to maintenance and harvesting, I'll share tips, tricks, and insights every step of the way.

## YouTube Channel

Don't forget to check out [The Green Yard YouTube channel](https://www.youtube.com/@thegreenyardaz) for video updates and tutorials. Subscribe to stay up-to-date with our latest projects and adventures!

## Blog

For those who prefer to read, I'll also be sharing regular updates and articles right here on the blog. Whether you're a seasoned gardener or just starting out, there's something for everyone. Be sure to bookmark this page and check back often for new content.

## Connect With Us

Follow us on social media for even more behind-the-scenes peeks and garden inspiration:

- [Instagram](https://www.instagram.com/thegreenyardaz/)
- [Facebook](https://www.facebook.com/thegreenyardaz/)
- [Twitter](https://twitter.com/thegreenyardaz/)

## Get in Touch

Have a question or suggestion? Want to share your own gardening journey? We'd love to hear from you! Drop us a line at [contact@thegreenyard.com](mailto:contact@thegreenyard.com) and let's connect.

Remember to live green, plant lots, and, of course, have fun!
